name: api_state_view
description: A simple and reusable Flutter widget for handling loading, error, empty and success API states.
version: 0.0.1
homepage: https://github.com/yourusername/api_state_view
repository: https://github.com/yourusername/api_state_view
issue_tracker: https://github.com/yourusername/api_state_view/issues

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:

topics:
  - flutter
  - state-management
  - loading
  - api
  - widget